export enum FormActionType {
    CREATE_FILE = "createFile",
    INSERT_TEXT = "insertText",
    RUN_SCRIPT = "runScript",
    UPDATE_FRONTMATTER = "updateFrontmatter",
    SUGGEST_MODAL = "suggestModal",
    GENERATE_FORM = "generateForm",
    OPEN_FILE = "openFile",
    OPEN_LINK = "openLink",
    EXECUTE_COMMAND = "executeCommand",
    AI_CALL = "aiCall",
    CONTENT_CLEANUP = "contentCleanup",
    COPY_AS_RICH_TEXT = "copyAsRichText",
    CONVERT_IMAGE_LINKS = "convertImageLinks",
    ADD_SPACES_BETWEEN_CJK_AND_LATIN = "addSpacesBetweenCjkAndLatin",
}
